server:
  port: 30000
spring:
  cloud:
    gateway:
      enabled: true
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: spring-cloud-gateway-template
#      routes:
#        - id: spring-demo
#          predicates:
#            - Host=**.foo.org
#            - Path=/headers
#            - Method=GET
#            - Header=X-Request-Id, d+
#            - Query=foo, ba.
#            - Query=baz
#            - Cookie=chocolate, ch.p
#            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
#          uri: http://www.zhihu.com
management:
  endpoints:
    web:
      exposure:
        include: gateway

